// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: mastertag.proto

package mastertag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MasterTagPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	FileName    string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileSize    int32  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	CryptoKey   string `protobuf:"bytes,4,opt,name=cryptoKey,proto3" json:"cryptoKey,omitempty"`
	DownloadUrl string `protobuf:"bytes,5,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
}

func (x *MasterTagPack) Reset() {
	*x = MasterTagPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mastertag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterTagPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterTagPack) ProtoMessage() {}

func (x *MasterTagPack) ProtoReflect() protoreflect.Message {
	mi := &file_mastertag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterTagPack.ProtoReflect.Descriptor instead.
func (*MasterTagPack) Descriptor() ([]byte, []int) {
	return file_mastertag_proto_rawDescGZIP(), []int{0}
}

func (x *MasterTagPack) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MasterTagPack) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MasterTagPack) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MasterTagPack) GetCryptoKey() string {
	if x != nil {
		return x.CryptoKey
	}
	return ""
}

func (x *MasterTagPack) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type MasterTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version        string           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	MasterTagPacks []*MasterTagPack `protobuf:"bytes,2,rep,name=masterTagPacks,proto3" json:"masterTagPacks,omitempty"`
}

func (x *MasterTag) Reset() {
	*x = MasterTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mastertag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterTag) ProtoMessage() {}

func (x *MasterTag) ProtoReflect() protoreflect.Message {
	mi := &file_mastertag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterTag.ProtoReflect.Descriptor instead.
func (*MasterTag) Descriptor() ([]byte, []int) {
	return file_mastertag_proto_rawDescGZIP(), []int{1}
}

func (x *MasterTag) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MasterTag) GetMasterTagPacks() []*MasterTagPack {
	if x != nil {
		return x.MasterTagPacks
	}
	return nil
}

type MasterGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MasterTag *MasterTag `protobuf:"bytes,1,opt,name=masterTag,proto3" json:"masterTag,omitempty"`
	ProtoHash string     `protobuf:"bytes,2,opt,name=protoHash,proto3" json:"protoHash,omitempty"`
}

func (x *MasterGetResponse) Reset() {
	*x = MasterGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mastertag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterGetResponse) ProtoMessage() {}

func (x *MasterGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mastertag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterGetResponse.ProtoReflect.Descriptor instead.
func (*MasterGetResponse) Descriptor() ([]byte, []int) {
	return file_mastertag_proto_rawDescGZIP(), []int{2}
}

func (x *MasterGetResponse) GetMasterTag() *MasterTag {
	if x != nil {
		return x.MasterTag
	}
	return nil
}

func (x *MasterGetResponse) GetProtoHash() string {
	if x != nil {
		return x.ProtoHash
	}
	return ""
}

var File_mastertag_proto protoreflect.FileDescriptor

var file_mastertag_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9b, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x50,
	0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x22,
	0x5d, 0x0a, 0x09, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x0e, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x54, 0x61, 0x67, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x50, 0x61, 0x63, 0x6b, 0x52, 0x0e,
	0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x50, 0x61, 0x63, 0x6b, 0x73, 0x22, 0x5b,
	0x0a, 0x11, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x61, 0x67, 0x52, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x67, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x48, 0x61, 0x73, 0x68, 0x42, 0x12, 0x5a, 0x10, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x74, 0x61, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mastertag_proto_rawDescOnce sync.Once
	file_mastertag_proto_rawDescData = file_mastertag_proto_rawDesc
)

func file_mastertag_proto_rawDescGZIP() []byte {
	file_mastertag_proto_rawDescOnce.Do(func() {
		file_mastertag_proto_rawDescData = protoimpl.X.CompressGZIP(file_mastertag_proto_rawDescData)
	})
	return file_mastertag_proto_rawDescData
}

var file_mastertag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mastertag_proto_goTypes = []interface{}{
	(*MasterTagPack)(nil),     // 0: MasterTagPack
	(*MasterTag)(nil),         // 1: MasterTag
	(*MasterGetResponse)(nil), // 2: MasterGetResponse
}
var file_mastertag_proto_depIdxs = []int32{
	0, // 0: MasterTag.masterTagPacks:type_name -> MasterTagPack
	1, // 1: MasterGetResponse.masterTag:type_name -> MasterTag
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mastertag_proto_init() }
func file_mastertag_proto_init() {
	if File_mastertag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mastertag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterTagPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mastertag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mastertag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mastertag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mastertag_proto_goTypes,
		DependencyIndexes: file_mastertag_proto_depIdxs,
		MessageInfos:      file_mastertag_proto_msgTypes,
	}.Build()
	File_mastertag_proto = out.File
	file_mastertag_proto_rawDesc = nil
	file_mastertag_proto_goTypes = nil
	file_mastertag_proto_depIdxs = nil
}
