// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: papicommon.proto

package papicommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	pcommon "vertesan/campus/proto/pcommon"
	penum "vertesan/campus/proto/penum"
	pmaster "vertesan/campus/proto/pmaster"
	ptransaction "vertesan/campus/proto/ptransaction"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DearnessStoryUnlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=characterId,proto3" json:"characterId,omitempty"`
	StoryId       string                 `protobuf:"bytes,2,opt,name=storyId,proto3" json:"storyId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DearnessStoryUnlock) Reset() {
	*x = DearnessStoryUnlock{}
	mi := &file_papicommon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DearnessStoryUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DearnessStoryUnlock) ProtoMessage() {}

func (x *DearnessStoryUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_papicommon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DearnessStoryUnlock.ProtoReflect.Descriptor instead.
func (*DearnessStoryUnlock) Descriptor() ([]byte, []int) {
	return file_papicommon_proto_rawDescGZIP(), []int{0}
}

func (x *DearnessStoryUnlock) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *DearnessStoryUnlock) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type Mission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     string                 `protobuf:"bytes,1,opt,name=missionId,proto3" json:"missionId,omitempty"`
	Threshold     int32                  `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mission) Reset() {
	*x = Mission{}
	mi := &file_papicommon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_papicommon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_papicommon_proto_rawDescGZIP(), []int{1}
}

func (x *Mission) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *Mission) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type PvpRateSeasonTop struct {
	state                   protoimpl.MessageState        `protogen:"open.v1"`
	StatusType              penum.PvpRateSeasonStatusType `protobuf:"varint,1,opt,name=statusType,proto3,enum=penum.PvpRateSeasonStatusType" json:"statusType,omitempty"`
	Rate                    int32                         `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Rank                    int32                         `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	MaxDailyPlayCount       int32                         `protobuf:"varint,4,opt,name=maxDailyPlayCount,proto3" json:"maxDailyPlayCount,omitempty"`
	RemainingDailyPlayCount int32                         `protobuf:"varint,5,opt,name=remainingDailyPlayCount,proto3" json:"remainingDailyPlayCount,omitempty"`
	CurrentSeasonStartTime  int64                         `protobuf:"varint,6,opt,name=currentSeasonStartTime,proto3" json:"currentSeasonStartTime,omitempty"`
	CurrentSeasonEndTime    int64                         `protobuf:"varint,7,opt,name=currentSeasonEndTime,proto3" json:"currentSeasonEndTime,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PvpRateSeasonTop) Reset() {
	*x = PvpRateSeasonTop{}
	mi := &file_papicommon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PvpRateSeasonTop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PvpRateSeasonTop) ProtoMessage() {}

func (x *PvpRateSeasonTop) ProtoReflect() protoreflect.Message {
	mi := &file_papicommon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PvpRateSeasonTop.ProtoReflect.Descriptor instead.
func (*PvpRateSeasonTop) Descriptor() ([]byte, []int) {
	return file_papicommon_proto_rawDescGZIP(), []int{2}
}

func (x *PvpRateSeasonTop) GetStatusType() penum.PvpRateSeasonStatusType {
	if x != nil {
		return x.StatusType
	}
	return penum.PvpRateSeasonStatusType(0)
}

func (x *PvpRateSeasonTop) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *PvpRateSeasonTop) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PvpRateSeasonTop) GetMaxDailyPlayCount() int32 {
	if x != nil {
		return x.MaxDailyPlayCount
	}
	return 0
}

func (x *PvpRateSeasonTop) GetRemainingDailyPlayCount() int32 {
	if x != nil {
		return x.RemainingDailyPlayCount
	}
	return 0
}

func (x *PvpRateSeasonTop) GetCurrentSeasonStartTime() int64 {
	if x != nil {
		return x.CurrentSeasonStartTime
	}
	return 0
}

func (x *PvpRateSeasonTop) GetCurrentSeasonEndTime() int64 {
	if x != nil {
		return x.CurrentSeasonEndTime
	}
	return 0
}

type RankReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpperRank     int32                  `protobuf:"varint,1,opt,name=upperRank,proto3" json:"upperRank,omitempty"`
	LowerRank     int32                  `protobuf:"varint,2,opt,name=lowerRank,proto3" json:"lowerRank,omitempty"`
	BorderScore   int64                  `protobuf:"varint,3,opt,name=borderScore,proto3" json:"borderScore,omitempty"`
	Rewards       []*pcommon.Reward      `protobuf:"bytes,4,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankReward) Reset() {
	*x = RankReward{}
	mi := &file_papicommon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankReward) ProtoMessage() {}

func (x *RankReward) ProtoReflect() protoreflect.Message {
	mi := &file_papicommon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankReward.ProtoReflect.Descriptor instead.
func (*RankReward) Descriptor() ([]byte, []int) {
	return file_papicommon_proto_rawDescGZIP(), []int{3}
}

func (x *RankReward) GetUpperRank() int32 {
	if x != nil {
		return x.UpperRank
	}
	return 0
}

func (x *RankReward) GetLowerRank() int32 {
	if x != nil {
		return x.LowerRank
	}
	return 0
}

func (x *RankReward) GetBorderScore() int64 {
	if x != nil {
		return x.BorderScore
	}
	return 0
}

func (x *RankReward) GetRewards() []*pcommon.Reward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type Response struct {
	state                 protoimpl.MessageState         `protogen:"open.v1"`
	UpdatedData           *UserData                      `protobuf:"bytes,1,opt,name=updatedData,proto3" json:"updatedData,omitempty"`
	DeletedData           *UserData                      `protobuf:"bytes,2,opt,name=deletedData,proto3" json:"deletedData,omitempty"`
	ClearMissions         []*pmaster.Mission             `protobuf:"bytes,3,rep,name=clearMissions,proto3" json:"clearMissions,omitempty"`
	ProducerLevelUnlocks  []*pcommon.ProducerLevelUnlock `protobuf:"bytes,4,rep,name=producerLevelUnlocks,proto3" json:"producerLevelUnlocks,omitempty"`
	DearnessStoryUnlocks  []*DearnessStoryUnlock         `protobuf:"bytes,5,rep,name=dearnessStoryUnlocks,proto3" json:"dearnessStoryUnlocks,omitempty"`
	AnotherCostumeIds     []string                       `protobuf:"bytes,6,rep,name=anotherCostumeIds,proto3" json:"anotherCostumeIds,omitempty"`
	AnotherCostumeHeadIds []string                       `protobuf:"bytes,7,rep,name=anotherCostumeHeadIds,proto3" json:"anotherCostumeHeadIds,omitempty"`
	StoryEventRewards     []*StoryEventReward            `protobuf:"bytes,8,rep,name=storyEventRewards,proto3" json:"storyEventRewards,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_papicommon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_papicommon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_papicommon_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetUpdatedData() *UserData {
	if x != nil {
		return x.UpdatedData
	}
	return nil
}

func (x *Response) GetDeletedData() *UserData {
	if x != nil {
		return x.DeletedData
	}
	return nil
}

func (x *Response) GetClearMissions() []*pmaster.Mission {
	if x != nil {
		return x.ClearMissions
	}
	return nil
}

func (x *Response) GetProducerLevelUnlocks() []*pcommon.ProducerLevelUnlock {
	if x != nil {
		return x.ProducerLevelUnlocks
	}
	return nil
}

func (x *Response) GetDearnessStoryUnlocks() []*DearnessStoryUnlock {
	if x != nil {
		return x.DearnessStoryUnlocks
	}
	return nil
}

func (x *Response) GetAnotherCostumeIds() []string {
	if x != nil {
		return x.AnotherCostumeIds
	}
	return nil
}

func (x *Response) GetAnotherCostumeHeadIds() []string {
	if x != nil {
		return x.AnotherCostumeHeadIds
	}
	return nil
}

func (x *Response) GetStoryEventRewards() []*StoryEventReward {
	if x != nil {
		return x.StoryEventRewards
	}
	return nil
}

type StoryEventReward struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	StoryEventId  string                           `protobuf:"bytes,1,opt,name=storyEventId,proto3" json:"storyEventId,omitempty"`
	PointRewards  []*pcommon.StoryEventPointReward `protobuf:"bytes,2,rep,name=pointRewards,proto3" json:"pointRewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryEventReward) Reset() {
	*x = StoryEventReward{}
	mi := &file_papicommon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryEventReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryEventReward) ProtoMessage() {}

func (x *StoryEventReward) ProtoReflect() protoreflect.Message {
	mi := &file_papicommon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryEventReward.ProtoReflect.Descriptor instead.
func (*StoryEventReward) Descriptor() ([]byte, []int) {
	return file_papicommon_proto_rawDescGZIP(), []int{5}
}

func (x *StoryEventReward) GetStoryEventId() string {
	if x != nil {
		return x.StoryEventId
	}
	return ""
}

func (x *StoryEventReward) GetPointRewards() []*pcommon.StoryEventPointReward {
	if x != nil {
		return x.PointRewards
	}
	return nil
}

type UserData struct {
	state                              protoimpl.MessageState                         `protogen:"open.v1"`
	User                               *ptransaction.User                             `protobuf:"bytes,342861366,opt,name=user,proto3" json:"user,omitempty"`
	UserActionPoint                    *ptransaction.UserActionPoint                  `protobuf:"bytes,238317234,opt,name=userActionPoint,proto3" json:"userActionPoint,omitempty"`
	UserAuthProviderList               []*ptransaction.UserAuthProvider               `protobuf:"bytes,151341701,rep,name=userAuthProviderList,proto3" json:"userAuthProviderList,omitempty"`
	UserBadgeList                      []*ptransaction.UserBadge                      `protobuf:"bytes,175219847,rep,name=userBadgeList,proto3" json:"userBadgeList,omitempty"`
	UserBalance                        *ptransaction.UserBalance                      `protobuf:"bytes,164091159,opt,name=userBalance,proto3" json:"userBalance,omitempty"`
	UserBanWarning                     *ptransaction.UserBanWarning                   `protobuf:"bytes,531719871,opt,name=userBanWarning,proto3" json:"userBanWarning,omitempty"`
	UserCharacterList                  []*ptransaction.UserCharacter                  `protobuf:"bytes,370704040,rep,name=userCharacterList,proto3" json:"userCharacterList,omitempty"`
	UserCharacterCostumeList           []*ptransaction.UserCharacterCostume           `protobuf:"bytes,314243425,rep,name=userCharacterCostumeList,proto3" json:"userCharacterCostumeList,omitempty"`
	UserCharacterRosterList            []*ptransaction.UserCharacterRoster            `protobuf:"bytes,449008014,rep,name=userCharacterRosterList,proto3" json:"userCharacterRosterList,omitempty"`
	UserComebackList                   []*ptransaction.UserComeback                   `protobuf:"bytes,440873335,rep,name=userComebackList,proto3" json:"userComebackList,omitempty"`
	UserCostumeList                    []*ptransaction.UserCostume                    `protobuf:"bytes,469968532,rep,name=userCostumeList,proto3" json:"userCostumeList,omitempty"`
	UserCostumeHeadList                []*ptransaction.UserCostumeHead                `protobuf:"bytes,374617052,rep,name=userCostumeHeadList,proto3" json:"userCostumeHeadList,omitempty"`
	UserCountList                      []*ptransaction.UserCount                      `protobuf:"bytes,431111247,rep,name=userCountList,proto3" json:"userCountList,omitempty"`
	UserDearnessStoryList              []*ptransaction.UserDearnessStory              `protobuf:"bytes,133642946,rep,name=userDearnessStoryList,proto3" json:"userDearnessStoryList,omitempty"`
	UserGashaButtonList                []*ptransaction.UserGashaButton                `protobuf:"bytes,319381230,rep,name=userGashaButtonList,proto3" json:"userGashaButtonList,omitempty"`
	UserGuild                          *ptransaction.UserGuild                        `protobuf:"bytes,33667889,opt,name=userGuild,proto3" json:"userGuild,omitempty"`
	UserHomeCharacterList              []*ptransaction.UserHomeCharacter              `protobuf:"bytes,88325184,rep,name=userHomeCharacterList,proto3" json:"userHomeCharacterList,omitempty"`
	UserIdolCardList                   []*ptransaction.UserIdolCard                   `protobuf:"bytes,119514127,rep,name=userIdolCardList,proto3" json:"userIdolCardList,omitempty"`
	UserIdolCardSkinList               []*ptransaction.UserIdolCardSkin               `protobuf:"bytes,77005383,rep,name=userIdolCardSkinList,proto3" json:"userIdolCardSkinList,omitempty"`
	UserInvitation                     *ptransaction.UserInvitation                   `protobuf:"bytes,11952121,opt,name=userInvitation,proto3" json:"userInvitation,omitempty"`
	UserItemList                       []*ptransaction.UserItem                       `protobuf:"bytes,208896283,rep,name=userItemList,proto3" json:"userItemList,omitempty"`
	UserMeishiList                     []*ptransaction.UserMeishi                     `protobuf:"bytes,392438043,rep,name=userMeishiList,proto3" json:"userMeishiList,omitempty"`
	UserMeishiBaseAssetList            []*ptransaction.UserMeishiBaseAsset            `protobuf:"bytes,10530785,rep,name=userMeishiBaseAssetList,proto3" json:"userMeishiBaseAssetList,omitempty"`
	UserMeishiIllustrationAssetList    []*ptransaction.UserMeishiIllustrationAsset    `protobuf:"bytes,100237367,rep,name=userMeishiIllustrationAssetList,proto3" json:"userMeishiIllustrationAssetList,omitempty"`
	UserMemoryList                     []*ptransaction.UserMemory                     `protobuf:"bytes,163783316,rep,name=userMemoryList,proto3" json:"userMemoryList,omitempty"`
	UserMemoryInherit                  *ptransaction.UserMemoryInherit                `protobuf:"bytes,312197620,opt,name=userMemoryInherit,proto3" json:"userMemoryInherit,omitempty"`
	UserMissionList                    []*ptransaction.UserMission                    `protobuf:"bytes,176225192,rep,name=userMissionList,proto3" json:"userMissionList,omitempty"`
	UserMissionDailyReleaseGroupList   []*ptransaction.UserMissionDailyReleaseGroup   `protobuf:"bytes,104872908,rep,name=userMissionDailyReleaseGroupList,proto3" json:"userMissionDailyReleaseGroupList,omitempty"`
	UserMissionGroupList               []*ptransaction.UserMissionGroup               `protobuf:"bytes,350034430,rep,name=userMissionGroupList,proto3" json:"userMissionGroupList,omitempty"`
	UserMissionPassList                []*ptransaction.UserMissionPass                `protobuf:"bytes,143481512,rep,name=userMissionPassList,proto3" json:"userMissionPassList,omitempty"`
	UserMissionPassPointList           []*ptransaction.UserMissionPassPoint           `protobuf:"bytes,358937978,rep,name=userMissionPassPointList,proto3" json:"userMissionPassPointList,omitempty"`
	UserMissionPointList               []*ptransaction.UserMissionPoint               `protobuf:"bytes,124548488,rep,name=userMissionPointList,proto3" json:"userMissionPointList,omitempty"`
	UserMoney                          *ptransaction.UserMoney                        `protobuf:"bytes,170538259,opt,name=userMoney,proto3" json:"userMoney,omitempty"`
	UserMovieList                      []*ptransaction.UserMovie                      `protobuf:"bytes,389419008,rep,name=userMovieList,proto3" json:"userMovieList,omitempty"`
	UserMusicList                      []*ptransaction.UserMusic                      `protobuf:"bytes,430828780,rep,name=userMusicList,proto3" json:"userMusicList,omitempty"`
	UserPhotoList                      []*ptransaction.UserPhoto                      `protobuf:"bytes,288232532,rep,name=userPhotoList,proto3" json:"userPhotoList,omitempty"`
	UserPhotoBackgroundList            []*ptransaction.UserPhotoBackground            `protobuf:"bytes,99273345,rep,name=userPhotoBackgroundList,proto3" json:"userPhotoBackgroundList,omitempty"`
	UserPhotoPoseList                  []*ptransaction.UserPhotoPose                  `protobuf:"bytes,439296203,rep,name=userPhotoPoseList,proto3" json:"userPhotoPoseList,omitempty"`
	UserPreference                     *ptransaction.UserPreference                   `protobuf:"bytes,296399830,opt,name=userPreference,proto3" json:"userPreference,omitempty"`
	UserProduceList                    []*ptransaction.UserProduce                    `protobuf:"bytes,170637697,rep,name=userProduceList,proto3" json:"userProduceList,omitempty"`
	UserProduceAdvList                 []*ptransaction.UserProduceAdv                 `protobuf:"bytes,280248182,rep,name=userProduceAdvList,proto3" json:"userProduceAdvList,omitempty"`
	UserProduceCardList                []*ptransaction.UserProduceCard                `protobuf:"bytes,230550472,rep,name=userProduceCardList,proto3" json:"userProduceCardList,omitempty"`
	UserProduceCardConversionList      []*ptransaction.UserProduceCardConversion      `protobuf:"bytes,238079855,rep,name=userProduceCardConversionList,proto3" json:"userProduceCardConversionList,omitempty"`
	UserProduceCardRewardList          []*ptransaction.UserProduceCardReward          `protobuf:"bytes,364806182,rep,name=userProduceCardRewardList,proto3" json:"userProduceCardRewardList,omitempty"`
	UserProduceCharacterList           []*ptransaction.UserProduceCharacter           `protobuf:"bytes,494627662,rep,name=userProduceCharacterList,proto3" json:"userProduceCharacterList,omitempty"`
	UserProduceDrinkList               []*ptransaction.UserProduceDrink               `protobuf:"bytes,65968245,rep,name=userProduceDrinkList,proto3" json:"userProduceDrinkList,omitempty"`
	UserProduceGroupCharacterList      []*ptransaction.UserProduceGroupCharacter      `protobuf:"bytes,149373425,rep,name=userProduceGroupCharacterList,proto3" json:"userProduceGroupCharacterList,omitempty"`
	UserProduceIdolCardList            []*ptransaction.UserProduceIdolCard            `protobuf:"bytes,110043881,rep,name=userProduceIdolCardList,proto3" json:"userProduceIdolCardList,omitempty"`
	UserProduceItemList                []*ptransaction.UserProduceItem                `protobuf:"bytes,99080460,rep,name=userProduceItemList,proto3" json:"userProduceItemList,omitempty"`
	UserProduceLiveList                []*ptransaction.UserProduceLive                `protobuf:"bytes,317020496,rep,name=userProduceLiveList,proto3" json:"userProduceLiveList,omitempty"`
	UserProduceMemoryDeckList          []*ptransaction.UserProduceMemoryDeck          `protobuf:"bytes,162217088,rep,name=userProduceMemoryDeckList,proto3" json:"userProduceMemoryDeckList,omitempty"`
	UserProduceProgress                *ptransaction.UserProduceProgress              `protobuf:"bytes,374217157,opt,name=userProduceProgress,proto3" json:"userProduceProgress,omitempty"`
	UserProduceProgressAudition        *ptransaction.UserProduceProgressAudition      `protobuf:"bytes,532050964,opt,name=userProduceProgressAudition,proto3" json:"userProduceProgressAudition,omitempty"`
	UserProduceProgressBusinessList    []*ptransaction.UserProduceProgressBusiness    `protobuf:"bytes,84290276,rep,name=userProduceProgressBusinessList,proto3" json:"userProduceProgressBusinessList,omitempty"`
	UserProduceProgressEffectList      []*ptransaction.UserProduceProgressEffect      `protobuf:"bytes,315942447,rep,name=userProduceProgressEffectList,proto3" json:"userProduceProgressEffectList,omitempty"`
	UserProduceProgressEventList       []*ptransaction.UserProduceProgressEvent       `protobuf:"bytes,40225152,rep,name=userProduceProgressEventList,proto3" json:"userProduceProgressEventList,omitempty"`
	UserProduceProgressMemoryList      []*ptransaction.UserProduceProgressMemory      `protobuf:"bytes,215423357,rep,name=userProduceProgressMemoryList,proto3" json:"userProduceProgressMemoryList,omitempty"`
	UserProduceProgressPresentList     []*ptransaction.UserProduceProgressPresent     `protobuf:"bytes,349962730,rep,name=userProduceProgressPresentList,proto3" json:"userProduceProgressPresentList,omitempty"`
	UserProduceProgressProduceCardList []*ptransaction.UserProduceProgressProduceCard `protobuf:"bytes,309641228,rep,name=userProduceProgressProduceCardList,proto3" json:"userProduceProgressProduceCardList,omitempty"`
	UserProduceProgressScheduleList    []*ptransaction.UserProduceProgressSchedule    `protobuf:"bytes,22482116,rep,name=userProduceProgressScheduleList,proto3" json:"userProduceProgressScheduleList,omitempty"`
	UserProduceProgressShopList        []*ptransaction.UserProduceProgressShop        `protobuf:"bytes,498183736,rep,name=userProduceProgressShopList,proto3" json:"userProduceProgressShopList,omitempty"`
	UserProduceProgressSupportCardList []*ptransaction.UserProduceProgressSupportCard `protobuf:"bytes,256246388,rep,name=userProduceProgressSupportCardList,proto3" json:"userProduceProgressSupportCardList,omitempty"`
	UserProduceRerollMemoryList        []*ptransaction.UserProduceRerollMemory        `protobuf:"bytes,440818481,rep,name=userProduceRerollMemoryList,proto3" json:"userProduceRerollMemoryList,omitempty"`
	UserProduceStartAchievementList    []*ptransaction.UserProduceStartAchievement    `protobuf:"bytes,259880526,rep,name=userProduceStartAchievementList,proto3" json:"userProduceStartAchievementList,omitempty"`
	UserProduceStoryList               []*ptransaction.UserProduceStory               `protobuf:"bytes,117364693,rep,name=userProduceStoryList,proto3" json:"userProduceStoryList,omitempty"`
	UserProduceSupportCardDeckList     []*ptransaction.UserProduceSupportCardDeck     `protobuf:"bytes,286307933,rep,name=userProduceSupportCardDeckList,proto3" json:"userProduceSupportCardDeckList,omitempty"`
	UserProfile                        *ptransaction.UserProfile                      `protobuf:"bytes,49977942,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	UserPvpRate                        *ptransaction.UserPvpRate                      `protobuf:"bytes,226209413,opt,name=userPvpRate,proto3" json:"userPvpRate,omitempty"`
	UserPvpRateUnit                    *ptransaction.UserPvpRateUnit                  `protobuf:"bytes,286467793,opt,name=userPvpRateUnit,proto3" json:"userPvpRateUnit,omitempty"`
	UserShopItemList                   []*ptransaction.UserShopItem                   `protobuf:"bytes,455613547,rep,name=userShopItemList,proto3" json:"userShopItemList,omitempty"`
	UserStoryList                      []*ptransaction.UserStory                      `protobuf:"bytes,376356693,rep,name=userStoryList,proto3" json:"userStoryList,omitempty"`
	UserSupportCardList                []*ptransaction.UserSupportCard                `protobuf:"bytes,2234692,rep,name=userSupportCardList,proto3" json:"userSupportCardList,omitempty"`
	UserTimeList                       []*ptransaction.UserTime                       `protobuf:"bytes,68970636,rep,name=userTimeList,proto3" json:"userTimeList,omitempty"`
	UserTowerList                      []*ptransaction.UserTower                      `protobuf:"bytes,268691409,rep,name=userTowerList,proto3" json:"userTowerList,omitempty"`
	UserTutorialList                   []*ptransaction.UserTutorial                   `protobuf:"bytes,201375606,rep,name=userTutorialList,proto3" json:"userTutorialList,omitempty"`
	UserWorkList                       []*ptransaction.UserWork                       `protobuf:"bytes,225189857,rep,name=userWorkList,proto3" json:"userWorkList,omitempty"`
	UserWorkCharacterList              []*ptransaction.UserWorkCharacter              `protobuf:"bytes,192688899,rep,name=userWorkCharacterList,proto3" json:"userWorkCharacterList,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_papicommon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_papicommon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_papicommon_proto_rawDescGZIP(), []int{6}
}

func (x *UserData) GetUser() *ptransaction.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserData) GetUserActionPoint() *ptransaction.UserActionPoint {
	if x != nil {
		return x.UserActionPoint
	}
	return nil
}

func (x *UserData) GetUserAuthProviderList() []*ptransaction.UserAuthProvider {
	if x != nil {
		return x.UserAuthProviderList
	}
	return nil
}

func (x *UserData) GetUserBadgeList() []*ptransaction.UserBadge {
	if x != nil {
		return x.UserBadgeList
	}
	return nil
}

func (x *UserData) GetUserBalance() *ptransaction.UserBalance {
	if x != nil {
		return x.UserBalance
	}
	return nil
}

func (x *UserData) GetUserBanWarning() *ptransaction.UserBanWarning {
	if x != nil {
		return x.UserBanWarning
	}
	return nil
}

func (x *UserData) GetUserCharacterList() []*ptransaction.UserCharacter {
	if x != nil {
		return x.UserCharacterList
	}
	return nil
}

func (x *UserData) GetUserCharacterCostumeList() []*ptransaction.UserCharacterCostume {
	if x != nil {
		return x.UserCharacterCostumeList
	}
	return nil
}

func (x *UserData) GetUserCharacterRosterList() []*ptransaction.UserCharacterRoster {
	if x != nil {
		return x.UserCharacterRosterList
	}
	return nil
}

func (x *UserData) GetUserComebackList() []*ptransaction.UserComeback {
	if x != nil {
		return x.UserComebackList
	}
	return nil
}

func (x *UserData) GetUserCostumeList() []*ptransaction.UserCostume {
	if x != nil {
		return x.UserCostumeList
	}
	return nil
}

func (x *UserData) GetUserCostumeHeadList() []*ptransaction.UserCostumeHead {
	if x != nil {
		return x.UserCostumeHeadList
	}
	return nil
}

func (x *UserData) GetUserCountList() []*ptransaction.UserCount {
	if x != nil {
		return x.UserCountList
	}
	return nil
}

func (x *UserData) GetUserDearnessStoryList() []*ptransaction.UserDearnessStory {
	if x != nil {
		return x.UserDearnessStoryList
	}
	return nil
}

func (x *UserData) GetUserGashaButtonList() []*ptransaction.UserGashaButton {
	if x != nil {
		return x.UserGashaButtonList
	}
	return nil
}

func (x *UserData) GetUserGuild() *ptransaction.UserGuild {
	if x != nil {
		return x.UserGuild
	}
	return nil
}

func (x *UserData) GetUserHomeCharacterList() []*ptransaction.UserHomeCharacter {
	if x != nil {
		return x.UserHomeCharacterList
	}
	return nil
}

func (x *UserData) GetUserIdolCardList() []*ptransaction.UserIdolCard {
	if x != nil {
		return x.UserIdolCardList
	}
	return nil
}

func (x *UserData) GetUserIdolCardSkinList() []*ptransaction.UserIdolCardSkin {
	if x != nil {
		return x.UserIdolCardSkinList
	}
	return nil
}

func (x *UserData) GetUserInvitation() *ptransaction.UserInvitation {
	if x != nil {
		return x.UserInvitation
	}
	return nil
}

func (x *UserData) GetUserItemList() []*ptransaction.UserItem {
	if x != nil {
		return x.UserItemList
	}
	return nil
}

func (x *UserData) GetUserMeishiList() []*ptransaction.UserMeishi {
	if x != nil {
		return x.UserMeishiList
	}
	return nil
}

func (x *UserData) GetUserMeishiBaseAssetList() []*ptransaction.UserMeishiBaseAsset {
	if x != nil {
		return x.UserMeishiBaseAssetList
	}
	return nil
}

func (x *UserData) GetUserMeishiIllustrationAssetList() []*ptransaction.UserMeishiIllustrationAsset {
	if x != nil {
		return x.UserMeishiIllustrationAssetList
	}
	return nil
}

func (x *UserData) GetUserMemoryList() []*ptransaction.UserMemory {
	if x != nil {
		return x.UserMemoryList
	}
	return nil
}

func (x *UserData) GetUserMemoryInherit() *ptransaction.UserMemoryInherit {
	if x != nil {
		return x.UserMemoryInherit
	}
	return nil
}

func (x *UserData) GetUserMissionList() []*ptransaction.UserMission {
	if x != nil {
		return x.UserMissionList
	}
	return nil
}

func (x *UserData) GetUserMissionDailyReleaseGroupList() []*ptransaction.UserMissionDailyReleaseGroup {
	if x != nil {
		return x.UserMissionDailyReleaseGroupList
	}
	return nil
}

func (x *UserData) GetUserMissionGroupList() []*ptransaction.UserMissionGroup {
	if x != nil {
		return x.UserMissionGroupList
	}
	return nil
}

func (x *UserData) GetUserMissionPassList() []*ptransaction.UserMissionPass {
	if x != nil {
		return x.UserMissionPassList
	}
	return nil
}

func (x *UserData) GetUserMissionPassPointList() []*ptransaction.UserMissionPassPoint {
	if x != nil {
		return x.UserMissionPassPointList
	}
	return nil
}

func (x *UserData) GetUserMissionPointList() []*ptransaction.UserMissionPoint {
	if x != nil {
		return x.UserMissionPointList
	}
	return nil
}

func (x *UserData) GetUserMoney() *ptransaction.UserMoney {
	if x != nil {
		return x.UserMoney
	}
	return nil
}

func (x *UserData) GetUserMovieList() []*ptransaction.UserMovie {
	if x != nil {
		return x.UserMovieList
	}
	return nil
}

func (x *UserData) GetUserMusicList() []*ptransaction.UserMusic {
	if x != nil {
		return x.UserMusicList
	}
	return nil
}

func (x *UserData) GetUserPhotoList() []*ptransaction.UserPhoto {
	if x != nil {
		return x.UserPhotoList
	}
	return nil
}

func (x *UserData) GetUserPhotoBackgroundList() []*ptransaction.UserPhotoBackground {
	if x != nil {
		return x.UserPhotoBackgroundList
	}
	return nil
}

func (x *UserData) GetUserPhotoPoseList() []*ptransaction.UserPhotoPose {
	if x != nil {
		return x.UserPhotoPoseList
	}
	return nil
}

func (x *UserData) GetUserPreference() *ptransaction.UserPreference {
	if x != nil {
		return x.UserPreference
	}
	return nil
}

func (x *UserData) GetUserProduceList() []*ptransaction.UserProduce {
	if x != nil {
		return x.UserProduceList
	}
	return nil
}

func (x *UserData) GetUserProduceAdvList() []*ptransaction.UserProduceAdv {
	if x != nil {
		return x.UserProduceAdvList
	}
	return nil
}

func (x *UserData) GetUserProduceCardList() []*ptransaction.UserProduceCard {
	if x != nil {
		return x.UserProduceCardList
	}
	return nil
}

func (x *UserData) GetUserProduceCardConversionList() []*ptransaction.UserProduceCardConversion {
	if x != nil {
		return x.UserProduceCardConversionList
	}
	return nil
}

func (x *UserData) GetUserProduceCardRewardList() []*ptransaction.UserProduceCardReward {
	if x != nil {
		return x.UserProduceCardRewardList
	}
	return nil
}

func (x *UserData) GetUserProduceCharacterList() []*ptransaction.UserProduceCharacter {
	if x != nil {
		return x.UserProduceCharacterList
	}
	return nil
}

func (x *UserData) GetUserProduceDrinkList() []*ptransaction.UserProduceDrink {
	if x != nil {
		return x.UserProduceDrinkList
	}
	return nil
}

func (x *UserData) GetUserProduceGroupCharacterList() []*ptransaction.UserProduceGroupCharacter {
	if x != nil {
		return x.UserProduceGroupCharacterList
	}
	return nil
}

func (x *UserData) GetUserProduceIdolCardList() []*ptransaction.UserProduceIdolCard {
	if x != nil {
		return x.UserProduceIdolCardList
	}
	return nil
}

func (x *UserData) GetUserProduceItemList() []*ptransaction.UserProduceItem {
	if x != nil {
		return x.UserProduceItemList
	}
	return nil
}

func (x *UserData) GetUserProduceLiveList() []*ptransaction.UserProduceLive {
	if x != nil {
		return x.UserProduceLiveList
	}
	return nil
}

func (x *UserData) GetUserProduceMemoryDeckList() []*ptransaction.UserProduceMemoryDeck {
	if x != nil {
		return x.UserProduceMemoryDeckList
	}
	return nil
}

func (x *UserData) GetUserProduceProgress() *ptransaction.UserProduceProgress {
	if x != nil {
		return x.UserProduceProgress
	}
	return nil
}

func (x *UserData) GetUserProduceProgressAudition() *ptransaction.UserProduceProgressAudition {
	if x != nil {
		return x.UserProduceProgressAudition
	}
	return nil
}

func (x *UserData) GetUserProduceProgressBusinessList() []*ptransaction.UserProduceProgressBusiness {
	if x != nil {
		return x.UserProduceProgressBusinessList
	}
	return nil
}

func (x *UserData) GetUserProduceProgressEffectList() []*ptransaction.UserProduceProgressEffect {
	if x != nil {
		return x.UserProduceProgressEffectList
	}
	return nil
}

func (x *UserData) GetUserProduceProgressEventList() []*ptransaction.UserProduceProgressEvent {
	if x != nil {
		return x.UserProduceProgressEventList
	}
	return nil
}

func (x *UserData) GetUserProduceProgressMemoryList() []*ptransaction.UserProduceProgressMemory {
	if x != nil {
		return x.UserProduceProgressMemoryList
	}
	return nil
}

func (x *UserData) GetUserProduceProgressPresentList() []*ptransaction.UserProduceProgressPresent {
	if x != nil {
		return x.UserProduceProgressPresentList
	}
	return nil
}

func (x *UserData) GetUserProduceProgressProduceCardList() []*ptransaction.UserProduceProgressProduceCard {
	if x != nil {
		return x.UserProduceProgressProduceCardList
	}
	return nil
}

func (x *UserData) GetUserProduceProgressScheduleList() []*ptransaction.UserProduceProgressSchedule {
	if x != nil {
		return x.UserProduceProgressScheduleList
	}
	return nil
}

func (x *UserData) GetUserProduceProgressShopList() []*ptransaction.UserProduceProgressShop {
	if x != nil {
		return x.UserProduceProgressShopList
	}
	return nil
}

func (x *UserData) GetUserProduceProgressSupportCardList() []*ptransaction.UserProduceProgressSupportCard {
	if x != nil {
		return x.UserProduceProgressSupportCardList
	}
	return nil
}

func (x *UserData) GetUserProduceRerollMemoryList() []*ptransaction.UserProduceRerollMemory {
	if x != nil {
		return x.UserProduceRerollMemoryList
	}
	return nil
}

func (x *UserData) GetUserProduceStartAchievementList() []*ptransaction.UserProduceStartAchievement {
	if x != nil {
		return x.UserProduceStartAchievementList
	}
	return nil
}

func (x *UserData) GetUserProduceStoryList() []*ptransaction.UserProduceStory {
	if x != nil {
		return x.UserProduceStoryList
	}
	return nil
}

func (x *UserData) GetUserProduceSupportCardDeckList() []*ptransaction.UserProduceSupportCardDeck {
	if x != nil {
		return x.UserProduceSupportCardDeckList
	}
	return nil
}

func (x *UserData) GetUserProfile() *ptransaction.UserProfile {
	if x != nil {
		return x.UserProfile
	}
	return nil
}

func (x *UserData) GetUserPvpRate() *ptransaction.UserPvpRate {
	if x != nil {
		return x.UserPvpRate
	}
	return nil
}

func (x *UserData) GetUserPvpRateUnit() *ptransaction.UserPvpRateUnit {
	if x != nil {
		return x.UserPvpRateUnit
	}
	return nil
}

func (x *UserData) GetUserShopItemList() []*ptransaction.UserShopItem {
	if x != nil {
		return x.UserShopItemList
	}
	return nil
}

func (x *UserData) GetUserStoryList() []*ptransaction.UserStory {
	if x != nil {
		return x.UserStoryList
	}
	return nil
}

func (x *UserData) GetUserSupportCardList() []*ptransaction.UserSupportCard {
	if x != nil {
		return x.UserSupportCardList
	}
	return nil
}

func (x *UserData) GetUserTimeList() []*ptransaction.UserTime {
	if x != nil {
		return x.UserTimeList
	}
	return nil
}

func (x *UserData) GetUserTowerList() []*ptransaction.UserTower {
	if x != nil {
		return x.UserTowerList
	}
	return nil
}

func (x *UserData) GetUserTutorialList() []*ptransaction.UserTutorial {
	if x != nil {
		return x.UserTutorialList
	}
	return nil
}

func (x *UserData) GetUserWorkList() []*ptransaction.UserWork {
	if x != nil {
		return x.UserWorkList
	}
	return nil
}

func (x *UserData) GetUserWorkCharacterList() []*ptransaction.UserWorkCharacter {
	if x != nil {
		return x.UserWorkCharacterList
	}
	return nil
}

var File_papicommon_proto protoreflect.FileDescriptor

const file_papicommon_proto_rawDesc = "" +
	"\n" +
	"\x10papicommon.proto\x12\n" +
	"papicommon\x1a\vpenum.proto\x1a\rpcommon.proto\x1a\x12ptransaction.proto\x1a\rpmaster.proto\"Q\n" +
	"\x13DearnessStoryUnlock\x12 \n" +
	"\vcharacterId\x18\x01 \x01(\tR\vcharacterId\x12\x18\n" +
	"\astoryId\x18\x02 \x01(\tR\astoryId\"E\n" +
	"\aMission\x12\x1c\n" +
	"\tmissionId\x18\x01 \x01(\tR\tmissionId\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x05R\tthreshold\"\xce\x02\n" +
	"\x10PvpRateSeasonTop\x12>\n" +
	"\n" +
	"statusType\x18\x01 \x01(\x0e2\x1e.penum.PvpRateSeasonStatusTypeR\n" +
	"statusType\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x05R\x04rate\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\x12,\n" +
	"\x11maxDailyPlayCount\x18\x04 \x01(\x05R\x11maxDailyPlayCount\x128\n" +
	"\x17remainingDailyPlayCount\x18\x05 \x01(\x05R\x17remainingDailyPlayCount\x126\n" +
	"\x16currentSeasonStartTime\x18\x06 \x01(\x03R\x16currentSeasonStartTime\x122\n" +
	"\x14currentSeasonEndTime\x18\a \x01(\x03R\x14currentSeasonEndTime\"\x95\x01\n" +
	"\n" +
	"RankReward\x12\x1c\n" +
	"\tupperRank\x18\x01 \x01(\x05R\tupperRank\x12\x1c\n" +
	"\tlowerRank\x18\x02 \x01(\x05R\tlowerRank\x12 \n" +
	"\vborderScore\x18\x03 \x01(\x03R\vborderScore\x12)\n" +
	"\arewards\x18\x04 \x03(\v2\x0f.pcommon.RewardR\arewards\"\x89\x04\n" +
	"\bResponse\x126\n" +
	"\vupdatedData\x18\x01 \x01(\v2\x14.papicommon.UserDataR\vupdatedData\x126\n" +
	"\vdeletedData\x18\x02 \x01(\v2\x14.papicommon.UserDataR\vdeletedData\x126\n" +
	"\rclearMissions\x18\x03 \x03(\v2\x10.pmaster.MissionR\rclearMissions\x12P\n" +
	"\x14producerLevelUnlocks\x18\x04 \x03(\v2\x1c.pcommon.ProducerLevelUnlockR\x14producerLevelUnlocks\x12S\n" +
	"\x14dearnessStoryUnlocks\x18\x05 \x03(\v2\x1f.papicommon.DearnessStoryUnlockR\x14dearnessStoryUnlocks\x12,\n" +
	"\x11anotherCostumeIds\x18\x06 \x03(\tR\x11anotherCostumeIds\x124\n" +
	"\x15anotherCostumeHeadIds\x18\a \x03(\tR\x15anotherCostumeHeadIds\x12J\n" +
	"\x11storyEventRewards\x18\b \x03(\v2\x1c.papicommon.StoryEventRewardR\x11storyEventRewards\"z\n" +
	"\x10StoryEventReward\x12\"\n" +
	"\fstoryEventId\x18\x01 \x01(\tR\fstoryEventId\x12B\n" +
	"\fpointRewards\x18\x02 \x03(\v2\x1e.pcommon.StoryEventPointRewardR\fpointRewards\"\xcf4\n" +
	"\bUserData\x12*\n" +
	"\x04user\x18\xb6̾\xa3\x01 \x01(\v2\x12.ptransaction.UserR\x04user\x12J\n" +
	"\x0fuserActionPoint\x18\xb2\xdd\xd1q \x01(\v2\x1d.ptransaction.UserActionPointR\x0fuserActionPoint\x12U\n" +
	"\x14userAuthProviderList\x18\x85\x95\x95H \x03(\v2\x1e.ptransaction.UserAuthProviderR\x14userAuthProviderList\x12@\n" +
	"\ruserBadgeList\x18\x87\xc9\xc6S \x03(\v2\x17.ptransaction.UserBadgeR\ruserBadgeList\x12>\n" +
	"\vuserBalance\x18\x97\xaa\x9fN \x01(\v2\x19.ptransaction.UserBalanceR\vuserBalance\x12H\n" +
	"\x0euserBanWarning\x18\xbf\xcd\xc5\xfd\x01 \x01(\v2\x1c.ptransaction.UserBanWarningR\x0euserBanWarning\x12M\n" +
	"\x11userCharacterList\x18\xa8\xfd\xe1\xb0\x01 \x03(\v2\x1b.ptransaction.UserCharacterR\x11userCharacterList\x12b\n" +
	"\x18userCharacterCostumeList\x18\xe1\xf2\xeb\x95\x01 \x03(\v2\".ptransaction.UserCharacterCostumeR\x18userCharacterCostumeList\x12_\n" +
	"\x17userCharacterRosterList\x18\x8e\xa3\x8d\xd6\x01 \x03(\v2!.ptransaction.UserCharacterRosterR\x17userCharacterRosterList\x12J\n" +
	"\x10userComebackList\x18\xf7\xe2\x9c\xd2\x01 \x03(\v2\x1a.ptransaction.UserComebackR\x10userComebackList\x12G\n" +
	"\x0fuserCostumeList\x18\x94͌\xe0\x01 \x03(\v2\x19.ptransaction.UserCostumeR\x0fuserCostumeList\x12S\n" +
	"\x13userCostumeHeadList\x18\xdc\xe7в\x01 \x03(\v2\x1d.ptransaction.UserCostumeHeadR\x13userCostumeHeadList\x12A\n" +
	"\ruserCountList\x18\xcf\xf8\xc8\xcd\x01 \x03(\v2\x17.ptransaction.UserCountR\ruserCountList\x12X\n" +
	"\x15userDearnessStoryList\x18\xc2\xf5\xdc? \x03(\v2\x1f.ptransaction.UserDearnessStoryR\x15userDearnessStoryList\x12S\n" +
	"\x13userGashaButtonList\x18\uef65\x98\x01 \x03(\v2\x1d.ptransaction.UserGashaButtonR\x13userGashaButtonList\x128\n" +
	"\tuserGuild\x18\xb1\xf6\x86\x10 \x01(\v2\x17.ptransaction.UserGuildR\tuserGuild\x12X\n" +
	"\x15userHomeCharacterList\x18\xc0\xf8\x8e* \x03(\v2\x1f.ptransaction.UserHomeCharacterR\x15userHomeCharacterList\x12I\n" +
	"\x10userIdolCardList\x18\x8f\xc8\xfe8 \x03(\v2\x1a.ptransaction.UserIdolCardR\x10userIdolCardList\x12U\n" +
	"\x14userIdolCardSkinList\x18Ǆ\xdc$ \x03(\v2\x1e.ptransaction.UserIdolCardSkinR\x14userIdolCardSkinList\x12G\n" +
	"\x0euserInvitation\x18\xf9\xbf\xd9\x05 \x01(\v2\x1c.ptransaction.UserInvitationR\x0euserInvitation\x12=\n" +
	"\fuserItemList\x18\x9b\x82\xcec \x03(\v2\x16.ptransaction.UserItemR\fuserItemList\x12D\n" +
	"\x0euserMeishiList\x18\x9b\u0090\xbb\x01 \x03(\v2\x18.ptransaction.UserMeishiR\x0euserMeishiList\x12^\n" +
	"\x17userMeishiBaseAssetList\x18\xe1߂\x05 \x03(\v2!.ptransaction.UserMeishiBaseAssetR\x17userMeishiBaseAssetList\x12v\n" +
	"\x1fuserMeishiIllustrationAssetList\x18\xb7\x80\xe6/ \x03(\v2).ptransaction.UserMeishiIllustrationAssetR\x1fuserMeishiIllustrationAssetList\x12C\n" +
	"\x0euserMemoryList\x18\x94ŌN \x03(\v2\x18.ptransaction.UserMemoryR\x0euserMemoryList\x12Q\n" +
	"\x11userMemoryInherit\x18\xf4\x83\xef\x94\x01 \x01(\v2\x1f.ptransaction.UserMemoryInheritR\x11userMemoryInherit\x12F\n" +
	"\x0fuserMissionList\x18\xa8\xf7\x83T \x03(\v2\x19.ptransaction.UserMissionR\x0fuserMissionList\x12y\n" +
	" userMissionDailyReleaseGroupList\x18\xcc\xf7\x802 \x03(\v2*.ptransaction.UserMissionDailyReleaseGroupR userMissionDailyReleaseGroupList\x12V\n" +
	"\x14userMissionGroupList\x18\xfe\xb3\xf4\xa6\x01 \x03(\v2\x1e.ptransaction.UserMissionGroupR\x14userMissionGroupList\x12R\n" +
	"\x13userMissionPassList\x18\xa8\xb5\xb5D \x03(\v2\x1d.ptransaction.UserMissionPassR\x13userMissionPassList\x12b\n" +
	"\x18userMissionPassPointList\x18\xfaꓫ\x01 \x03(\v2\".ptransaction.UserMissionPassPointR\x18userMissionPassPointList\x12U\n" +
	"\x14userMissionPointList\x18\x88\xeb\xb1; \x03(\v2\x1e.ptransaction.UserMissionPointR\x14userMissionPointList\x128\n" +
	"\tuserMoney\x18\x93\xea\xa8Q \x01(\v2\x17.ptransaction.UserMoneyR\tuserMoney\x12A\n" +
	"\ruserMovieList\x18\x80\xa0ع\x01 \x03(\v2\x17.ptransaction.UserMovieR\ruserMovieList\x12A\n" +
	"\ruserMusicList\x18\xecٷ\xcd\x01 \x03(\v2\x17.ptransaction.UserMusicR\ruserMusicList\x12A\n" +
	"\ruserPhotoList\x18Ԩ\xb8\x89\x01 \x03(\v2\x17.ptransaction.UserPhotoR\ruserPhotoList\x12^\n" +
	"\x17userPhotoBackgroundList\x18\x81\x95\xab/ \x03(\v2!.ptransaction.UserPhotoBackgroundR\x17userPhotoBackgroundList\x12M\n" +
	"\x11userPhotoPoseList\x18\xcb\xc1\xbc\xd1\x01 \x03(\v2\x1b.ptransaction.UserPhotoPoseR\x11userPhotoPoseList\x12H\n" +
	"\x0euserPreference\x18\xd6窍\x01 \x01(\v2\x1c.ptransaction.UserPreferenceR\x0euserPreference\x12F\n" +
	"\x0fuserProduceList\x18\x81\xf3\xaeQ \x03(\v2\x19.ptransaction.UserProduceR\x0fuserProduceList\x12P\n" +
	"\x12userProduceAdvList\x18\xf6\xfeЅ\x01 \x03(\v2\x1c.ptransaction.UserProduceAdvR\x12userProduceAdvList\x12R\n" +
	"\x13userProduceCardList\x18\xc8\xd7\xf7m \x03(\v2\x1d.ptransaction.UserProduceCardR\x13userProduceCardList\x12p\n" +
	"\x1duserProduceCardConversionList\x18\xef\x9e\xc3q \x03(\v2'.ptransaction.UserProduceCardConversionR\x1duserProduceCardConversionList\x12e\n" +
	"\x19userProduceCardRewardList\x18\xa6\x80\xfa\xad\x01 \x03(\v2#.ptransaction.UserProduceCardRewardR\x19userProduceCardRewardList\x12b\n" +
	"\x18userProduceCharacterList\x18\xce\xd6\xed\xeb\x01 \x03(\v2\".ptransaction.UserProduceCharacterR\x18userProduceCharacterList\x12U\n" +
	"\x14userProduceDrinkList\x18\xf5\xb0\xba\x1f \x03(\v2\x1e.ptransaction.UserProduceDrinkR\x14userProduceDrinkList\x12p\n" +
	"\x1duserProduceGroupCharacterList\x18\xf1\x83\x9dG \x03(\v2'.ptransaction.UserProduceGroupCharacterR\x1duserProduceGroupCharacterList\x12^\n" +
	"\x17userProduceIdolCardList\x18\xe9ż4 \x03(\v2!.ptransaction.UserProduceIdolCardR\x17userProduceIdolCardList\x12R\n" +
	"\x13userProduceItemList\x18\x8c\xb2\x9f/ \x03(\v2\x1d.ptransaction.UserProduceItemR\x13userProduceItemList\x12S\n" +
	"\x13userProduceLiveList\x18в\x95\x97\x01 \x03(\v2\x1d.ptransaction.UserProduceLiveR\x13userProduceLiveList\x12d\n" +
	"\x19userProduceMemoryDeckList\x18\x80\xf9\xacM \x03(\v2#.ptransaction.UserProduceMemoryDeckR\x19userProduceMemoryDeckList\x12W\n" +
	"\x13userProduceProgress\x18ų\xb8\xb2\x01 \x01(\v2!.ptransaction.UserProduceProgressR\x13userProduceProgress\x12o\n" +
	"\x1buserProduceProgressAudition\x18\x94\xe8\xd9\xfd\x01 \x01(\v2).ptransaction.UserProduceProgressAuditionR\x1buserProduceProgressAudition\x12v\n" +
	"\x1fuserProduceProgressBusinessList\x18\xe4\u0558( \x03(\v2).ptransaction.UserProduceProgressBusinessR\x1fuserProduceProgressBusinessList\x12q\n" +
	"\x1duserProduceProgressEffectList\x18\xaf\xccӖ\x01 \x03(\v2'.ptransaction.UserProduceProgressEffectR\x1duserProduceProgressEffectList\x12m\n" +
	"\x1cuserProduceProgressEventList\x18\x80\x93\x97\x13 \x03(\v2&.ptransaction.UserProduceProgressEventR\x1cuserProduceProgressEventList\x12p\n" +
	"\x1duserProduceProgressMemoryList\x18\xfd\xb2\xdcf \x03(\v2'.ptransaction.UserProduceProgressMemoryR\x1duserProduceProgressMemoryList\x12t\n" +
	"\x1euserProduceProgressPresentList\x18\xea\x83\xf0\xa6\x01 \x03(\v2(.ptransaction.UserProduceProgressPresentR\x1euserProduceProgressPresentList\x12\x80\x01\n" +
	"\"userProduceProgressProduceCardList\x18\x8c\x80ӓ\x01 \x03(\v2,.ptransaction.UserProduceProgressProduceCardR\"userProduceProgressProduceCardList\x12v\n" +
	"\x1fuserProduceProgressScheduleList\x18ę\xdc\n" +
	" \x03(\v2).ptransaction.UserProduceProgressScheduleR\x1fuserProduceProgressScheduleList\x12k\n" +
	"\x1buserProduceProgressShopList\x18\xb8\xdc\xc6\xed\x01 \x03(\v2%.ptransaction.UserProduceProgressShopR\x1buserProduceProgressShopList\x12\x7f\n" +
	"\"userProduceProgressSupportCardList\x18\xf4\x84\x98z \x03(\v2,.ptransaction.UserProduceProgressSupportCardR\"userProduceProgressSupportCardList\x12k\n" +
	"\x1buserProduceRerollMemoryList\x18\xb1\xb6\x99\xd2\x01 \x03(\v2%.ptransaction.UserProduceRerollMemoryR\x1buserProduceRerollMemoryList\x12v\n" +
	"\x1fuserProduceStartAchievementList\x18\xce\xec\xf5{ \x03(\v2).ptransaction.UserProduceStartAchievementR\x1fuserProduceStartAchievementList\x12U\n" +
	"\x14userProduceStoryList\x18կ\xfb7 \x03(\v2\x1e.ptransaction.UserProduceStoryR\x14userProduceStoryList\x12t\n" +
	"\x1euserProduceSupportCardDeckList\x18\xdd\xec\u0088\x01 \x03(\v2(.ptransaction.UserProduceSupportCardDeckR\x1euserProduceSupportCardDeckList\x12>\n" +
	"\vuserProfile\x18ִ\xea\x17 \x01(\v2\x19.ptransaction.UserProfileR\vuserProfile\x12>\n" +
	"\vuserPvpRate\x18\x85\xdd\xeek \x01(\v2\x19.ptransaction.UserPvpRateR\vuserPvpRate\x12K\n" +
	"\x0fuserPvpRateUnit\x18\xd1\xcd̈\x01 \x01(\v2\x1d.ptransaction.UserPvpRateUnitR\x0fuserPvpRateUnit\x12J\n" +
	"\x10userShopItemList\x18븠\xd9\x01 \x03(\v2\x1a.ptransaction.UserShopItemR\x10userShopItemList\x12A\n" +
	"\ruserStoryList\x18\xd5\xfe\xba\xb3\x01 \x03(\v2\x17.ptransaction.UserStoryR\ruserStoryList\x12R\n" +
	"\x13userSupportCardList\x18Ĳ\x88\x01 \x03(\v2\x1d.ptransaction.UserSupportCardR\x13userSupportCardList\x12=\n" +
	"\fuserTimeList\x18\x8c\xd1\xf1  \x03(\v2\x16.ptransaction.UserTimeR\fuserTimeList\x12A\n" +
	"\ruserTowerList\x18\xd1Ϗ\x80\x01 \x03(\v2\x17.ptransaction.UserTowerR\ruserTowerList\x12I\n" +
	"\x10userTutorialList\x18\xf6\xfe\x82` \x03(\v2\x1a.ptransaction.UserTutorialR\x10userTutorialList\x12=\n" +
	"\fuserWorkList\x18\u1ff0k \x03(\v2\x16.ptransaction.UserWorkR\fuserWorkList\x12X\n" +
	"\x15userWorkCharacterList\x18\x83\xe6\xf0[ \x03(\v2\x1f.ptransaction.UserWorkCharacterR\x15userWorkCharacterListB\"Z vertesan/campus/proto/papicommonb\x06proto3"

var (
	file_papicommon_proto_rawDescOnce sync.Once
	file_papicommon_proto_rawDescData []byte
)

func file_papicommon_proto_rawDescGZIP() []byte {
	file_papicommon_proto_rawDescOnce.Do(func() {
		file_papicommon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_papicommon_proto_rawDesc), len(file_papicommon_proto_rawDesc)))
	})
	return file_papicommon_proto_rawDescData
}

var file_papicommon_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_papicommon_proto_goTypes = []any{
	(*DearnessStoryUnlock)(nil),                         // 0: papicommon.DearnessStoryUnlock
	(*Mission)(nil),                                     // 1: papicommon.Mission
	(*PvpRateSeasonTop)(nil),                            // 2: papicommon.PvpRateSeasonTop
	(*RankReward)(nil),                                  // 3: papicommon.RankReward
	(*Response)(nil),                                    // 4: papicommon.Response
	(*StoryEventReward)(nil),                            // 5: papicommon.StoryEventReward
	(*UserData)(nil),                                    // 6: papicommon.UserData
	(penum.PvpRateSeasonStatusType)(0),                  // 7: penum.PvpRateSeasonStatusType
	(*pcommon.Reward)(nil),                              // 8: pcommon.Reward
	(*pmaster.Mission)(nil),                             // 9: pmaster.Mission
	(*pcommon.ProducerLevelUnlock)(nil),                 // 10: pcommon.ProducerLevelUnlock
	(*pcommon.StoryEventPointReward)(nil),               // 11: pcommon.StoryEventPointReward
	(*ptransaction.User)(nil),                           // 12: ptransaction.User
	(*ptransaction.UserActionPoint)(nil),                // 13: ptransaction.UserActionPoint
	(*ptransaction.UserAuthProvider)(nil),               // 14: ptransaction.UserAuthProvider
	(*ptransaction.UserBadge)(nil),                      // 15: ptransaction.UserBadge
	(*ptransaction.UserBalance)(nil),                    // 16: ptransaction.UserBalance
	(*ptransaction.UserBanWarning)(nil),                 // 17: ptransaction.UserBanWarning
	(*ptransaction.UserCharacter)(nil),                  // 18: ptransaction.UserCharacter
	(*ptransaction.UserCharacterCostume)(nil),           // 19: ptransaction.UserCharacterCostume
	(*ptransaction.UserCharacterRoster)(nil),            // 20: ptransaction.UserCharacterRoster
	(*ptransaction.UserComeback)(nil),                   // 21: ptransaction.UserComeback
	(*ptransaction.UserCostume)(nil),                    // 22: ptransaction.UserCostume
	(*ptransaction.UserCostumeHead)(nil),                // 23: ptransaction.UserCostumeHead
	(*ptransaction.UserCount)(nil),                      // 24: ptransaction.UserCount
	(*ptransaction.UserDearnessStory)(nil),              // 25: ptransaction.UserDearnessStory
	(*ptransaction.UserGashaButton)(nil),                // 26: ptransaction.UserGashaButton
	(*ptransaction.UserGuild)(nil),                      // 27: ptransaction.UserGuild
	(*ptransaction.UserHomeCharacter)(nil),              // 28: ptransaction.UserHomeCharacter
	(*ptransaction.UserIdolCard)(nil),                   // 29: ptransaction.UserIdolCard
	(*ptransaction.UserIdolCardSkin)(nil),               // 30: ptransaction.UserIdolCardSkin
	(*ptransaction.UserInvitation)(nil),                 // 31: ptransaction.UserInvitation
	(*ptransaction.UserItem)(nil),                       // 32: ptransaction.UserItem
	(*ptransaction.UserMeishi)(nil),                     // 33: ptransaction.UserMeishi
	(*ptransaction.UserMeishiBaseAsset)(nil),            // 34: ptransaction.UserMeishiBaseAsset
	(*ptransaction.UserMeishiIllustrationAsset)(nil),    // 35: ptransaction.UserMeishiIllustrationAsset
	(*ptransaction.UserMemory)(nil),                     // 36: ptransaction.UserMemory
	(*ptransaction.UserMemoryInherit)(nil),              // 37: ptransaction.UserMemoryInherit
	(*ptransaction.UserMission)(nil),                    // 38: ptransaction.UserMission
	(*ptransaction.UserMissionDailyReleaseGroup)(nil),   // 39: ptransaction.UserMissionDailyReleaseGroup
	(*ptransaction.UserMissionGroup)(nil),               // 40: ptransaction.UserMissionGroup
	(*ptransaction.UserMissionPass)(nil),                // 41: ptransaction.UserMissionPass
	(*ptransaction.UserMissionPassPoint)(nil),           // 42: ptransaction.UserMissionPassPoint
	(*ptransaction.UserMissionPoint)(nil),               // 43: ptransaction.UserMissionPoint
	(*ptransaction.UserMoney)(nil),                      // 44: ptransaction.UserMoney
	(*ptransaction.UserMovie)(nil),                      // 45: ptransaction.UserMovie
	(*ptransaction.UserMusic)(nil),                      // 46: ptransaction.UserMusic
	(*ptransaction.UserPhoto)(nil),                      // 47: ptransaction.UserPhoto
	(*ptransaction.UserPhotoBackground)(nil),            // 48: ptransaction.UserPhotoBackground
	(*ptransaction.UserPhotoPose)(nil),                  // 49: ptransaction.UserPhotoPose
	(*ptransaction.UserPreference)(nil),                 // 50: ptransaction.UserPreference
	(*ptransaction.UserProduce)(nil),                    // 51: ptransaction.UserProduce
	(*ptransaction.UserProduceAdv)(nil),                 // 52: ptransaction.UserProduceAdv
	(*ptransaction.UserProduceCard)(nil),                // 53: ptransaction.UserProduceCard
	(*ptransaction.UserProduceCardConversion)(nil),      // 54: ptransaction.UserProduceCardConversion
	(*ptransaction.UserProduceCardReward)(nil),          // 55: ptransaction.UserProduceCardReward
	(*ptransaction.UserProduceCharacter)(nil),           // 56: ptransaction.UserProduceCharacter
	(*ptransaction.UserProduceDrink)(nil),               // 57: ptransaction.UserProduceDrink
	(*ptransaction.UserProduceGroupCharacter)(nil),      // 58: ptransaction.UserProduceGroupCharacter
	(*ptransaction.UserProduceIdolCard)(nil),            // 59: ptransaction.UserProduceIdolCard
	(*ptransaction.UserProduceItem)(nil),                // 60: ptransaction.UserProduceItem
	(*ptransaction.UserProduceLive)(nil),                // 61: ptransaction.UserProduceLive
	(*ptransaction.UserProduceMemoryDeck)(nil),          // 62: ptransaction.UserProduceMemoryDeck
	(*ptransaction.UserProduceProgress)(nil),            // 63: ptransaction.UserProduceProgress
	(*ptransaction.UserProduceProgressAudition)(nil),    // 64: ptransaction.UserProduceProgressAudition
	(*ptransaction.UserProduceProgressBusiness)(nil),    // 65: ptransaction.UserProduceProgressBusiness
	(*ptransaction.UserProduceProgressEffect)(nil),      // 66: ptransaction.UserProduceProgressEffect
	(*ptransaction.UserProduceProgressEvent)(nil),       // 67: ptransaction.UserProduceProgressEvent
	(*ptransaction.UserProduceProgressMemory)(nil),      // 68: ptransaction.UserProduceProgressMemory
	(*ptransaction.UserProduceProgressPresent)(nil),     // 69: ptransaction.UserProduceProgressPresent
	(*ptransaction.UserProduceProgressProduceCard)(nil), // 70: ptransaction.UserProduceProgressProduceCard
	(*ptransaction.UserProduceProgressSchedule)(nil),    // 71: ptransaction.UserProduceProgressSchedule
	(*ptransaction.UserProduceProgressShop)(nil),        // 72: ptransaction.UserProduceProgressShop
	(*ptransaction.UserProduceProgressSupportCard)(nil), // 73: ptransaction.UserProduceProgressSupportCard
	(*ptransaction.UserProduceRerollMemory)(nil),        // 74: ptransaction.UserProduceRerollMemory
	(*ptransaction.UserProduceStartAchievement)(nil),    // 75: ptransaction.UserProduceStartAchievement
	(*ptransaction.UserProduceStory)(nil),               // 76: ptransaction.UserProduceStory
	(*ptransaction.UserProduceSupportCardDeck)(nil),     // 77: ptransaction.UserProduceSupportCardDeck
	(*ptransaction.UserProfile)(nil),                    // 78: ptransaction.UserProfile
	(*ptransaction.UserPvpRate)(nil),                    // 79: ptransaction.UserPvpRate
	(*ptransaction.UserPvpRateUnit)(nil),                // 80: ptransaction.UserPvpRateUnit
	(*ptransaction.UserShopItem)(nil),                   // 81: ptransaction.UserShopItem
	(*ptransaction.UserStory)(nil),                      // 82: ptransaction.UserStory
	(*ptransaction.UserSupportCard)(nil),                // 83: ptransaction.UserSupportCard
	(*ptransaction.UserTime)(nil),                       // 84: ptransaction.UserTime
	(*ptransaction.UserTower)(nil),                      // 85: ptransaction.UserTower
	(*ptransaction.UserTutorial)(nil),                   // 86: ptransaction.UserTutorial
	(*ptransaction.UserWork)(nil),                       // 87: ptransaction.UserWork
	(*ptransaction.UserWorkCharacter)(nil),              // 88: ptransaction.UserWorkCharacter
}
var file_papicommon_proto_depIdxs = []int32{
	7,  // 0: papicommon.PvpRateSeasonTop.statusType:type_name -> penum.PvpRateSeasonStatusType
	8,  // 1: papicommon.RankReward.rewards:type_name -> pcommon.Reward
	6,  // 2: papicommon.Response.updatedData:type_name -> papicommon.UserData
	6,  // 3: papicommon.Response.deletedData:type_name -> papicommon.UserData
	9,  // 4: papicommon.Response.clearMissions:type_name -> pmaster.Mission
	10, // 5: papicommon.Response.producerLevelUnlocks:type_name -> pcommon.ProducerLevelUnlock
	0,  // 6: papicommon.Response.dearnessStoryUnlocks:type_name -> papicommon.DearnessStoryUnlock
	5,  // 7: papicommon.Response.storyEventRewards:type_name -> papicommon.StoryEventReward
	11, // 8: papicommon.StoryEventReward.pointRewards:type_name -> pcommon.StoryEventPointReward
	12, // 9: papicommon.UserData.user:type_name -> ptransaction.User
	13, // 10: papicommon.UserData.userActionPoint:type_name -> ptransaction.UserActionPoint
	14, // 11: papicommon.UserData.userAuthProviderList:type_name -> ptransaction.UserAuthProvider
	15, // 12: papicommon.UserData.userBadgeList:type_name -> ptransaction.UserBadge
	16, // 13: papicommon.UserData.userBalance:type_name -> ptransaction.UserBalance
	17, // 14: papicommon.UserData.userBanWarning:type_name -> ptransaction.UserBanWarning
	18, // 15: papicommon.UserData.userCharacterList:type_name -> ptransaction.UserCharacter
	19, // 16: papicommon.UserData.userCharacterCostumeList:type_name -> ptransaction.UserCharacterCostume
	20, // 17: papicommon.UserData.userCharacterRosterList:type_name -> ptransaction.UserCharacterRoster
	21, // 18: papicommon.UserData.userComebackList:type_name -> ptransaction.UserComeback
	22, // 19: papicommon.UserData.userCostumeList:type_name -> ptransaction.UserCostume
	23, // 20: papicommon.UserData.userCostumeHeadList:type_name -> ptransaction.UserCostumeHead
	24, // 21: papicommon.UserData.userCountList:type_name -> ptransaction.UserCount
	25, // 22: papicommon.UserData.userDearnessStoryList:type_name -> ptransaction.UserDearnessStory
	26, // 23: papicommon.UserData.userGashaButtonList:type_name -> ptransaction.UserGashaButton
	27, // 24: papicommon.UserData.userGuild:type_name -> ptransaction.UserGuild
	28, // 25: papicommon.UserData.userHomeCharacterList:type_name -> ptransaction.UserHomeCharacter
	29, // 26: papicommon.UserData.userIdolCardList:type_name -> ptransaction.UserIdolCard
	30, // 27: papicommon.UserData.userIdolCardSkinList:type_name -> ptransaction.UserIdolCardSkin
	31, // 28: papicommon.UserData.userInvitation:type_name -> ptransaction.UserInvitation
	32, // 29: papicommon.UserData.userItemList:type_name -> ptransaction.UserItem
	33, // 30: papicommon.UserData.userMeishiList:type_name -> ptransaction.UserMeishi
	34, // 31: papicommon.UserData.userMeishiBaseAssetList:type_name -> ptransaction.UserMeishiBaseAsset
	35, // 32: papicommon.UserData.userMeishiIllustrationAssetList:type_name -> ptransaction.UserMeishiIllustrationAsset
	36, // 33: papicommon.UserData.userMemoryList:type_name -> ptransaction.UserMemory
	37, // 34: papicommon.UserData.userMemoryInherit:type_name -> ptransaction.UserMemoryInherit
	38, // 35: papicommon.UserData.userMissionList:type_name -> ptransaction.UserMission
	39, // 36: papicommon.UserData.userMissionDailyReleaseGroupList:type_name -> ptransaction.UserMissionDailyReleaseGroup
	40, // 37: papicommon.UserData.userMissionGroupList:type_name -> ptransaction.UserMissionGroup
	41, // 38: papicommon.UserData.userMissionPassList:type_name -> ptransaction.UserMissionPass
	42, // 39: papicommon.UserData.userMissionPassPointList:type_name -> ptransaction.UserMissionPassPoint
	43, // 40: papicommon.UserData.userMissionPointList:type_name -> ptransaction.UserMissionPoint
	44, // 41: papicommon.UserData.userMoney:type_name -> ptransaction.UserMoney
	45, // 42: papicommon.UserData.userMovieList:type_name -> ptransaction.UserMovie
	46, // 43: papicommon.UserData.userMusicList:type_name -> ptransaction.UserMusic
	47, // 44: papicommon.UserData.userPhotoList:type_name -> ptransaction.UserPhoto
	48, // 45: papicommon.UserData.userPhotoBackgroundList:type_name -> ptransaction.UserPhotoBackground
	49, // 46: papicommon.UserData.userPhotoPoseList:type_name -> ptransaction.UserPhotoPose
	50, // 47: papicommon.UserData.userPreference:type_name -> ptransaction.UserPreference
	51, // 48: papicommon.UserData.userProduceList:type_name -> ptransaction.UserProduce
	52, // 49: papicommon.UserData.userProduceAdvList:type_name -> ptransaction.UserProduceAdv
	53, // 50: papicommon.UserData.userProduceCardList:type_name -> ptransaction.UserProduceCard
	54, // 51: papicommon.UserData.userProduceCardConversionList:type_name -> ptransaction.UserProduceCardConversion
	55, // 52: papicommon.UserData.userProduceCardRewardList:type_name -> ptransaction.UserProduceCardReward
	56, // 53: papicommon.UserData.userProduceCharacterList:type_name -> ptransaction.UserProduceCharacter
	57, // 54: papicommon.UserData.userProduceDrinkList:type_name -> ptransaction.UserProduceDrink
	58, // 55: papicommon.UserData.userProduceGroupCharacterList:type_name -> ptransaction.UserProduceGroupCharacter
	59, // 56: papicommon.UserData.userProduceIdolCardList:type_name -> ptransaction.UserProduceIdolCard
	60, // 57: papicommon.UserData.userProduceItemList:type_name -> ptransaction.UserProduceItem
	61, // 58: papicommon.UserData.userProduceLiveList:type_name -> ptransaction.UserProduceLive
	62, // 59: papicommon.UserData.userProduceMemoryDeckList:type_name -> ptransaction.UserProduceMemoryDeck
	63, // 60: papicommon.UserData.userProduceProgress:type_name -> ptransaction.UserProduceProgress
	64, // 61: papicommon.UserData.userProduceProgressAudition:type_name -> ptransaction.UserProduceProgressAudition
	65, // 62: papicommon.UserData.userProduceProgressBusinessList:type_name -> ptransaction.UserProduceProgressBusiness
	66, // 63: papicommon.UserData.userProduceProgressEffectList:type_name -> ptransaction.UserProduceProgressEffect
	67, // 64: papicommon.UserData.userProduceProgressEventList:type_name -> ptransaction.UserProduceProgressEvent
	68, // 65: papicommon.UserData.userProduceProgressMemoryList:type_name -> ptransaction.UserProduceProgressMemory
	69, // 66: papicommon.UserData.userProduceProgressPresentList:type_name -> ptransaction.UserProduceProgressPresent
	70, // 67: papicommon.UserData.userProduceProgressProduceCardList:type_name -> ptransaction.UserProduceProgressProduceCard
	71, // 68: papicommon.UserData.userProduceProgressScheduleList:type_name -> ptransaction.UserProduceProgressSchedule
	72, // 69: papicommon.UserData.userProduceProgressShopList:type_name -> ptransaction.UserProduceProgressShop
	73, // 70: papicommon.UserData.userProduceProgressSupportCardList:type_name -> ptransaction.UserProduceProgressSupportCard
	74, // 71: papicommon.UserData.userProduceRerollMemoryList:type_name -> ptransaction.UserProduceRerollMemory
	75, // 72: papicommon.UserData.userProduceStartAchievementList:type_name -> ptransaction.UserProduceStartAchievement
	76, // 73: papicommon.UserData.userProduceStoryList:type_name -> ptransaction.UserProduceStory
	77, // 74: papicommon.UserData.userProduceSupportCardDeckList:type_name -> ptransaction.UserProduceSupportCardDeck
	78, // 75: papicommon.UserData.userProfile:type_name -> ptransaction.UserProfile
	79, // 76: papicommon.UserData.userPvpRate:type_name -> ptransaction.UserPvpRate
	80, // 77: papicommon.UserData.userPvpRateUnit:type_name -> ptransaction.UserPvpRateUnit
	81, // 78: papicommon.UserData.userShopItemList:type_name -> ptransaction.UserShopItem
	82, // 79: papicommon.UserData.userStoryList:type_name -> ptransaction.UserStory
	83, // 80: papicommon.UserData.userSupportCardList:type_name -> ptransaction.UserSupportCard
	84, // 81: papicommon.UserData.userTimeList:type_name -> ptransaction.UserTime
	85, // 82: papicommon.UserData.userTowerList:type_name -> ptransaction.UserTower
	86, // 83: papicommon.UserData.userTutorialList:type_name -> ptransaction.UserTutorial
	87, // 84: papicommon.UserData.userWorkList:type_name -> ptransaction.UserWork
	88, // 85: papicommon.UserData.userWorkCharacterList:type_name -> ptransaction.UserWorkCharacter
	86, // [86:86] is the sub-list for method output_type
	86, // [86:86] is the sub-list for method input_type
	86, // [86:86] is the sub-list for extension type_name
	86, // [86:86] is the sub-list for extension extendee
	0,  // [0:86] is the sub-list for field type_name
}

func init() { file_papicommon_proto_init() }
func file_papicommon_proto_init() {
	if File_papicommon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_papicommon_proto_rawDesc), len(file_papicommon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_papicommon_proto_goTypes,
		DependencyIndexes: file_papicommon_proto_depIdxs,
		MessageInfos:      file_papicommon_proto_msgTypes,
	}.Build()
	File_papicommon_proto = out.File
	file_papicommon_proto_goTypes = nil
	file_papicommon_proto_depIdxs = nil
}
