// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: octodb.proto

package octo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data_State int32

const (
	Data_NONE   Data_State = 0
	Data_ADD    Data_State = 1
	Data_UPDATE Data_State = 2
	Data_LATEST Data_State = 3
	Data_DELETE Data_State = 4
)

// Enum value maps for Data_State.
var (
	Data_State_name = map[int32]string{
		0: "NONE",
		1: "ADD",
		2: "UPDATE",
		3: "LATEST",
		4: "DELETE",
	}
	Data_State_value = map[string]int32{
		"NONE":   0,
		"ADD":    1,
		"UPDATE": 2,
		"LATEST": 3,
		"DELETE": 4,
	}
)

func (x Data_State) Enum() *Data_State {
	p := new(Data_State)
	*p = x
	return p
}

func (x Data_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_State) Descriptor() protoreflect.EnumDescriptor {
	return file_octodb_proto_enumTypes[0].Descriptor()
}

func (Data_State) Type() protoreflect.EnumType {
	return &file_octodb_proto_enumTypes[0]
}

func (x Data_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_State.Descriptor instead.
func (Data_State) EnumDescriptor() ([]byte, []int) {
	return file_octodb_proto_rawDescGZIP(), []int{1, 0}
}

type Database struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Revision        int32    `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	AssetBundleList []*Data  `protobuf:"bytes,2,rep,name=assetBundleList,proto3" json:"assetBundleList,omitempty"`
	Tagname         []string `protobuf:"bytes,3,rep,name=tagname,proto3" json:"tagname,omitempty"`
	ResourceList    []*Data  `protobuf:"bytes,4,rep,name=resourceList,proto3" json:"resourceList,omitempty"`
	UrlFormat       string   `protobuf:"bytes,5,opt,name=urlFormat,proto3" json:"urlFormat,omitempty"`
}

func (x *Database) Reset() {
	*x = Database{}
	if protoimpl.UnsafeEnabled {
		mi := &file_octodb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_octodb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_octodb_proto_rawDescGZIP(), []int{0}
}

func (x *Database) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Database) GetAssetBundleList() []*Data {
	if x != nil {
		return x.AssetBundleList
	}
	return nil
}

func (x *Database) GetTagname() []string {
	if x != nil {
		return x.Tagname
	}
	return nil
}

func (x *Database) GetResourceList() []*Data {
	if x != nil {
		return x.ResourceList
	}
	return nil
}

func (x *Database) GetUrlFormat() string {
	if x != nil {
		return x.UrlFormat
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filepath        string     `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Name            string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size            int32      `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Crc             uint32     `protobuf:"varint,5,opt,name=crc,proto3" json:"crc,omitempty"`
	Priority        int32      `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Tagid           []int32    `protobuf:"varint,7,rep,packed,name=tagid,proto3" json:"tagid,omitempty"`
	Dependencie     []int32    `protobuf:"varint,8,rep,packed,name=dependencie,proto3" json:"dependencie,omitempty"`
	State           Data_State `protobuf:"varint,9,opt,name=state,proto3,enum=Data_State" json:"state,omitempty"`
	Md5             string     `protobuf:"bytes,10,opt,name=md5,proto3" json:"md5,omitempty"`
	ObjectName      string     `protobuf:"bytes,11,opt,name=objectName,proto3" json:"objectName,omitempty"`
	Generation      uint64     `protobuf:"varint,12,opt,name=generation,proto3" json:"generation,omitempty"`
	UploadVersionId int32      `protobuf:"varint,13,opt,name=uploadVersionId,proto3" json:"uploadVersionId,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_octodb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_octodb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_octodb_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Data) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Data) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Data) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *Data) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Data) GetTagid() []int32 {
	if x != nil {
		return x.Tagid
	}
	return nil
}

func (x *Data) GetDependencie() []int32 {
	if x != nil {
		return x.Dependencie
	}
	return nil
}

func (x *Data) GetState() Data_State {
	if x != nil {
		return x.State
	}
	return Data_NONE
}

func (x *Data) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *Data) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *Data) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Data) GetUploadVersionId() int32 {
	if x != nil {
		return x.UploadVersionId
	}
	return 0
}

var File_octodb_proto protoreflect.FileDescriptor

var file_octodb_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x63, 0x74, 0x6f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba,
	0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72,
	0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x42, 0x75,
	0x6e, 0x64, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x29, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x72, 0x6c, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x72, 0x6c, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x9f, 0x03, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x63, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63, 0x72, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x67, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x74, 0x61, 0x67, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x0b, 0x64, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x12, 0x21,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x64, 0x35, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x75, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x3e, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44,
	0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x41, 0x54, 0x45, 0x53, 0x54, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04, 0x42, 0x0d, 0x5a,
	0x0b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x63, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_octodb_proto_rawDescOnce sync.Once
	file_octodb_proto_rawDescData = file_octodb_proto_rawDesc
)

func file_octodb_proto_rawDescGZIP() []byte {
	file_octodb_proto_rawDescOnce.Do(func() {
		file_octodb_proto_rawDescData = protoimpl.X.CompressGZIP(file_octodb_proto_rawDescData)
	})
	return file_octodb_proto_rawDescData
}

var file_octodb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_octodb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_octodb_proto_goTypes = []interface{}{
	(Data_State)(0),  // 0: Data.State
	(*Database)(nil), // 1: Database
	(*Data)(nil),     // 2: Data
}
var file_octodb_proto_depIdxs = []int32{
	2, // 0: Database.assetBundleList:type_name -> Data
	2, // 1: Database.resourceList:type_name -> Data
	0, // 2: Data.state:type_name -> Data.State
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_octodb_proto_init() }
func file_octodb_proto_init() {
	if File_octodb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_octodb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_octodb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_octodb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_octodb_proto_goTypes,
		DependencyIndexes: file_octodb_proto_depIdxs,
		EnumInfos:         file_octodb_proto_enumTypes,
		MessageInfos:      file_octodb_proto_msgTypes,
	}.Build()
	File_octodb_proto = out.File
	file_octodb_proto_rawDesc = nil
	file_octodb_proto_goTypes = nil
	file_octodb_proto_depIdxs = nil
}
