// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: octodb.proto

package octo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data_State int32

const (
	Data_NONE   Data_State = 0
	Data_ADD    Data_State = 1
	Data_UPDATE Data_State = 2
	Data_LATEST Data_State = 3
	Data_DELETE Data_State = 4
)

// Enum value maps for Data_State.
var (
	Data_State_name = map[int32]string{
		0: "NONE",
		1: "ADD",
		2: "UPDATE",
		3: "LATEST",
		4: "DELETE",
	}
	Data_State_value = map[string]int32{
		"NONE":   0,
		"ADD":    1,
		"UPDATE": 2,
		"LATEST": 3,
		"DELETE": 4,
	}
)

func (x Data_State) Enum() *Data_State {
	p := new(Data_State)
	*p = x
	return p
}

func (x Data_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Data_State) Descriptor() protoreflect.EnumDescriptor {
	return file_octodb_proto_enumTypes[0].Descriptor()
}

func (Data_State) Type() protoreflect.EnumType {
	return &file_octodb_proto_enumTypes[0]
}

func (x Data_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Data_State.Descriptor instead.
func (Data_State) EnumDescriptor() ([]byte, []int) {
	return file_octodb_proto_rawDescGZIP(), []int{1, 0}
}

type Database struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Revision        int32                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	AssetBundleList []*Data                `protobuf:"bytes,2,rep,name=assetBundleList,proto3" json:"assetBundleList,omitempty"`
	Tagname         []string               `protobuf:"bytes,3,rep,name=tagname,proto3" json:"tagname,omitempty"`
	ResourceList    []*Data                `protobuf:"bytes,4,rep,name=resourceList,proto3" json:"resourceList,omitempty"`
	UrlFormat       string                 `protobuf:"bytes,5,opt,name=urlFormat,proto3" json:"urlFormat,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_octodb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_octodb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_octodb_proto_rawDescGZIP(), []int{0}
}

func (x *Database) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Database) GetAssetBundleList() []*Data {
	if x != nil {
		return x.AssetBundleList
	}
	return nil
}

func (x *Database) GetTagname() []string {
	if x != nil {
		return x.Tagname
	}
	return nil
}

func (x *Database) GetResourceList() []*Data {
	if x != nil {
		return x.ResourceList
	}
	return nil
}

func (x *Database) GetUrlFormat() string {
	if x != nil {
		return x.UrlFormat
	}
	return ""
}

type Data struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Filepath        string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Size            int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Crc             uint32                 `protobuf:"varint,5,opt,name=crc,proto3" json:"crc,omitempty"`
	Priority        int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Tagid           []int32                `protobuf:"varint,7,rep,packed,name=tagid,proto3" json:"tagid,omitempty"`
	Dependencie     []int32                `protobuf:"varint,8,rep,packed,name=dependencie,proto3" json:"dependencie,omitempty"`
	State           Data_State             `protobuf:"varint,9,opt,name=state,proto3,enum=Data_State" json:"state,omitempty"`
	Md5             string                 `protobuf:"bytes,10,opt,name=md5,proto3" json:"md5,omitempty"`
	ObjectName      string                 `protobuf:"bytes,11,opt,name=objectName,proto3" json:"objectName,omitempty"`
	Generation      uint64                 `protobuf:"varint,12,opt,name=generation,proto3" json:"generation,omitempty"`
	UploadVersionId int32                  `protobuf:"varint,13,opt,name=uploadVersionId,proto3" json:"uploadVersionId,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_octodb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_octodb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_octodb_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Data) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *Data) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Data) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Data) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *Data) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Data) GetTagid() []int32 {
	if x != nil {
		return x.Tagid
	}
	return nil
}

func (x *Data) GetDependencie() []int32 {
	if x != nil {
		return x.Dependencie
	}
	return nil
}

func (x *Data) GetState() Data_State {
	if x != nil {
		return x.State
	}
	return Data_NONE
}

func (x *Data) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *Data) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *Data) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Data) GetUploadVersionId() int32 {
	if x != nil {
		return x.UploadVersionId
	}
	return 0
}

var File_octodb_proto protoreflect.FileDescriptor

const file_octodb_proto_rawDesc = "" +
	"\n" +
	"\foctodb.proto\"\xba\x01\n" +
	"\bDatabase\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x05R\brevision\x12/\n" +
	"\x0fassetBundleList\x18\x02 \x03(\v2\x05.DataR\x0fassetBundleList\x12\x18\n" +
	"\atagname\x18\x03 \x03(\tR\atagname\x12)\n" +
	"\fresourceList\x18\x04 \x03(\v2\x05.DataR\fresourceList\x12\x1c\n" +
	"\turlFormat\x18\x05 \x01(\tR\turlFormat\"\x9f\x03\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12\x10\n" +
	"\x03crc\x18\x05 \x01(\rR\x03crc\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x14\n" +
	"\x05tagid\x18\a \x03(\x05R\x05tagid\x12 \n" +
	"\vdependencie\x18\b \x03(\x05R\vdependencie\x12!\n" +
	"\x05state\x18\t \x01(\x0e2\v.Data.StateR\x05state\x12\x10\n" +
	"\x03md5\x18\n" +
	" \x01(\tR\x03md5\x12\x1e\n" +
	"\n" +
	"objectName\x18\v \x01(\tR\n" +
	"objectName\x12\x1e\n" +
	"\n" +
	"generation\x18\f \x01(\x04R\n" +
	"generation\x12(\n" +
	"\x0fuploadVersionId\x18\r \x01(\x05R\x0fuploadVersionId\">\n" +
	"\x05State\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03ADD\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\n" +
	"\n" +
	"\x06LATEST\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04B\rZ\v/proto/octob\x06proto3"

var (
	file_octodb_proto_rawDescOnce sync.Once
	file_octodb_proto_rawDescData []byte
)

func file_octodb_proto_rawDescGZIP() []byte {
	file_octodb_proto_rawDescOnce.Do(func() {
		file_octodb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_octodb_proto_rawDesc), len(file_octodb_proto_rawDesc)))
	})
	return file_octodb_proto_rawDescData
}

var file_octodb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_octodb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_octodb_proto_goTypes = []any{
	(Data_State)(0),  // 0: Data.State
	(*Database)(nil), // 1: Database
	(*Data)(nil),     // 2: Data
}
var file_octodb_proto_depIdxs = []int32{
	2, // 0: Database.assetBundleList:type_name -> Data
	2, // 1: Database.resourceList:type_name -> Data
	0, // 2: Data.state:type_name -> Data.State
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_octodb_proto_init() }
func file_octodb_proto_init() {
	if File_octodb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octodb_proto_rawDesc), len(file_octodb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_octodb_proto_goTypes,
		DependencyIndexes: file_octodb_proto_depIdxs,
		EnumInfos:         file_octodb_proto_enumTypes,
		MessageInfos:      file_octodb_proto_msgTypes,
	}.Build()
	File_octodb_proto = out.File
	file_octodb_proto_goTypes = nil
	file_octodb_proto_depIdxs = nil
}
